### ISSUE TITLE
AAR file issue

### ISSUE THREAD

**Issue by UjjawalPanchal** [ajinasokan/flutter_curl#1]
Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :flutter_curl project caused this error: E:\curl_demo_new\build\flutter_curl\libs\curl.aar.

I am getting this error while running the project. I have added plugin directly in pubspec.yaml.

**Comment by ajinasokan** [comment]
Could you post the Flutter & Gradle versions? 

This seems like an issue with new Gradle plugin. I will try to reproduce it with your setup.

**Comment by UjjawalPanchal** [comment]
Sure

classpath 'com.android.tools.build:gradle:4.1.0'

gradle-6.7-all.zip

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git

**Comment by UjjawalPanchal** [comment]
Hello, can it be possible to solve this issue in the latest Gradle version?

**Comment by ajinasokan** [comment]
To make it work temporarily you will have to downgrade to:
`classpath 'com.android.tools.build:gradle:3.5.0'`
and
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip`

**Comment by UjjawalPanchal** [comment]
Yes, I managed with the same but I also have to use <queries> tag in AndroidManifest.xml, and it is not allowed in this Gradle version.

**Comment by ajinasokan** [comment]
@UjjawalPanchal I have fixed this in the new version. Try to upgrade to `0.1.1` and see if that works.

**Comment by UjjawalPanchal** [comment]
@ajinasokan  Thank you for the quick update, it is working.
