### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by xAffan** [ajinasokan/flutter_curl#11]
curl can connect to proxy so this library should too.

**Comment by ajinasokan** [comment]
This is doable. Will check this out.

**Comment by xAffan** [comment]
Did you get around this?

**Comment by ajinasokan** [comment]
This is now available in master. You can set the proxy for whole` curl.Client` or individual request using the `proxy` params. Internally this sets the libcurl `CURLOPT_PROXY` flag. Could you try this out? I will be making a release with couple of other patches.
