### ISSUE TITLE
How to use on desktop?

### ISSUE THREAD

**Issue by meisme-dev** [ajinasokan/flutter_curl#2]
On desktop, it says 
`Failed to load dynamic library '/home/meisme/AndroidStudioProjects/minebird/build/linux/x64/debug/bundle/lib/libcurl.so': /home/meisme/AndroidStudioProjects/minebird/build/linux/x64/debug/bundle/lib/libcurl.so: cannot open shared object file: No such file or directory`
I know there's a .so file in Releases, but I'm unsure where to place it. Do I manually place the file every time I build?

**Comment by ajinasokan** [comment]
It should've downloaded the shared lib automatically. I have added that in the cmakelists https://github.com/ajinasokan/flutter_curl/blob/master/linux/CMakeLists.txt#L21

Did you see any errors while building? May be try `flutter build -v`? Also try building after a clean.
