### ISSUE TITLE
How to get verbose info

### ISSUE THREAD

**Issue by rickhan** [ajinasokan/flutter_curl#7]
Hi,
   I'm new to flutter_curl, but I use curl a lot, can you tell me how to use flutter_curl to retrive verbose info, just like get output from ```curl -v $url```

**Comment by ajinasokan** [comment]
You can enable it while creating the Client. https://github.com/ajinasokan/flutter_curl/blob/master/lib/src/client.dart#L50

**Comment by rickhan** [comment]
> You can enable it while creating the Client. https://github.com/ajinasokan/flutter_curl/blob/master/lib/src/client.dart#L50

I mean can I retrive verbose info by code? not watch verbose from logs, is that possible?

**Comment by ajinasokan** [comment]
You could use the `logsFor` function and give the your Request object. It will return back a stream of logs. https://github.com/ajinasokan/flutter_curl/blob/master/lib/src/client.dart#L46
