### ISSUE TITLE
Package not usable with the latest Flutter version

### ISSUE THREAD

**Issue by jusuf-el** [ajinasokan/flutter_curl#8]
This is what I get as soon as I import the package into a project file. This happens even with the latest dependency version.

`../../../../.pub-cache/hosted/pub.dev/flutter_curl-0.1.1/lib/src/ffi.dart:12:8: Error: Field 'messageType' cannot be nullable or have type 'Null', it must be `int`,
`double`, `Pointer`, or a subtype of `Struct` or `Union`.
  int? messageType;
       ^
../../../../.pub-cache/hosted/pub.dev/flutter_curl-0.1.1/lib/src/ffi.dart:14:27: Error: Field 'easyHandle' cannot be nullable or have type 'Null', it must be `int`,
`double`, `Pointer`, or a subtype of `Struct` or `Union`.
  ffi.Pointer<_CURLEasy>? easyHandle;
                          ^
../../../../.pub-cache/hosted/pub.dev/flutter_curl-0.1.1/lib/src/ffi.dart:17:8: Error: Field 'result' cannot be nullable or have type 'Null', it must be `int`, `double`,
`Pointer`, or a subtype of `Struct` or `Union`.
  int? result;
       ^
`

**Comment by ajinasokan** [comment]
Pushed an update with Flutter 3.10 migration. Try `flutter_curl: ^0.3.0`
